services:
  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: libretranslate
    ports:
      - "5000:5000"
    volumes:
      - libretranslate_data:/home/libretranslate/.local
    environment:
      - LT_LOAD_ONLY=en,fr,de,hi,id,it,pt,ru,es,vi  # Charger uniquement les langues nécessaires (fortement recommandé)
      - LT_API_KEYS=false         # Passer à true si vous souhaitez restreindre l'accès par clé
      - LT_REQ_LIMIT=60           # Limite le nombre de requêtes par minute par client
    restart: unless-stopped

volumes:
  libretranslate_data: